<?php

declare(strict_types=1);

namespace HomeEdu;

use PDO;

final class PilotContentApi
{
    private const ROUTE='david-fractions-grade-4-v1';

    public static function installDavidFractions(PDO $db,string $studentId): never
    {
        $session=Auth::requireRole($db,'parent');$familyId=(string)$session['family_id'];$actorId=(string)$session['user_id'];
        $student=self::one($db,'SELECT id,display_name,grade FROM students WHERE id=:id AND family_id=:family_id AND deleted_at IS NULL',['id'=>$studentId,'family_id'=>$familyId]);
        if(!$student)Http::error('not_found','Ученик не найден',404);if((int)$student['grade']!==4)Http::error('wrong_grade','Этот маршрут предназначен для 4 класса',409);
        $existing=self::one($db,'SELECT curriculum_id FROM pilot_content_installs WHERE student_id=:student_id AND route_code=:route',['student_id'=>$studentId,'route'=>self::ROUTE]);
        if($existing)Http::json(['installed'=>false,'alreadyInstalled'=>true,'curriculumId'=>$existing['curriculum_id'],'routeCode'=>self::ROUTE]);
        $db->beginTransaction();
        try{
            $subjectId=self::subject($db,$familyId);$curriculumId=self::curriculum($db,$familyId,$studentId);$assignmentId=self::assignment($db,$familyId,$curriculumId,$subjectId);
            $sectionId=self::insert($db,'INSERT INTO sections(id,family_id,curriculum_subject_id,title,description,position) VALUES(:id,:family_id,:parent,:title,:description,0)',['family_id'=>$familyId,'parent'=>$assignmentId,'title'=>'Дроби','description'=>'Пилотный маршрут: от части целого к простым действиям с дробями.']);
            $definitions=self::definitions();$previousCompetency=null;$counts=['topics'=>0,'lessons'=>0,'competencies'=>0,'quizzes'=>0,'homeworks'=>0];
            foreach($definitions as $topicPosition=>$topic){
                $topicId=self::insert($db,'INSERT INTO topics(id,family_id,section_id,title,description,position) VALUES(:id,:family_id,:parent,:title,:description,:position)',['family_id'=>$familyId,'parent'=>$sectionId,'title'=>$topic['title'],'description'=>$topic['description'],'position'=>$topicPosition]);$counts['topics']++;
                foreach($topic['competencies'] as $competency){$competencyId=self::insert($db,'INSERT INTO competencies(id,family_id,topic_id,title,description) VALUES(:id,:family_id,:parent,:title,:description)',['family_id'=>$familyId,'parent'=>$topicId,'title'=>$competency,'description'=>'Проверяется практикой, объяснением и повторением.']);if($previousCompetency)$db->prepare('INSERT INTO competency_prerequisites(competency_id,prerequisite_id,family_id) VALUES(:id,:required,:family_id)')->execute(['id'=>$competencyId,'required'=>$previousCompetency,'family_id'=>$familyId]);$previousCompetency=$competencyId;$counts['competencies']++;}
                foreach($topic['lessons'] as $lessonPosition=>$lesson){
                    $lessonId=self::insert($db,'INSERT INTO lessons(id,family_id,topic_id,title,summary,estimated_minutes,position,status) VALUES(:id,:family_id,:parent,:title,:summary,:minutes,:position,\'published\')',['family_id'=>$familyId,'parent'=>$topicId,'title'=>$lesson['title'],'summary'=>$lesson['summary'],'minutes'=>15,'position'=>$lessonPosition]);$counts['lessons']++;
                    foreach($lesson['blocks'] as $position=>$block)self::insert($db,'INSERT INTO content_blocks(id,family_id,lesson_id,block_type,content_json,position) VALUES(:id,:family_id,:parent,:type,:content,:position)',['family_id'=>$familyId,'parent'=>$lessonId,'type'=>$position===1?'example':'markdown','content'=>json_encode(['text'=>$block],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),'position'=>$position]);
                    $activityId=self::insert($db,'INSERT INTO activities(id,family_id,lesson_id,activity_type,title,position) VALUES(:id,:family_id,:parent,\'quiz\',:title,10)',['family_id'=>$familyId,'parent'=>$lessonId,'title'=>'Быстрая проверка']);$question=$lesson['quiz'];
                    self::insert($db,'INSERT INTO quiz_questions(id,family_id,activity_id,prompt,question_type,options_json,correct_answer_json,explanation) VALUES(:id,:family_id,:parent,:prompt,:type,:options,:answer,:explanation)',['family_id'=>$familyId,'parent'=>$activityId,'prompt'=>$question['prompt'],'type'=>$question['type'],'options'=>isset($question['options'])?json_encode($question['options'],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR):null,'answer'=>json_encode($question['answer'],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),'explanation'=>$question['explanation']]);$counts['quizzes']++;
                    if(isset($lesson['homework'])){self::insert($db,'INSERT INTO activities(id,family_id,lesson_id,activity_type,title,instructions,position) VALUES(:id,:family_id,:parent,\'open_work\',:title,:instructions,20)',['family_id'=>$familyId,'parent'=>$lessonId,'title'=>$lesson['homework']['title'],'instructions'=>$lesson['homework']['instructions']]);$counts['homeworks']++;}
                }
            }
            $db->prepare('INSERT INTO subject_mastery_settings(id,family_id,curriculum_subject_id,min_evidence_count,min_successful_types,review_interval_days) VALUES(:id,:family_id,:assignment,2,2,3) ON DUPLICATE KEY UPDATE min_evidence_count=2,min_successful_types=2,review_interval_days=3')->execute(['id'=>Uuid::v4(),'family_id'=>$familyId,'assignment'=>$assignmentId]);
            $db->prepare('INSERT INTO pilot_content_installs(id,family_id,student_id,route_code,curriculum_id) VALUES(:id,:family_id,:student_id,:route,:curriculum_id)')->execute(['id'=>Uuid::v4(),'family_id'=>$familyId,'student_id'=>$studentId,'route'=>self::ROUTE,'curriculum_id'=>$curriculumId]);
            Audit::record($db,$familyId,'parent',$actorId,'pilot_content.installed','student',$studentId,['routeCode'=>self::ROUTE,...$counts]);$db->commit();
        }catch(\Throwable $error){$db->rollBack();throw $error;}
        Http::json(['installed'=>true,'alreadyInstalled'=>false,'curriculumId'=>$curriculumId,'routeCode'=>self::ROUTE,'counts'=>$counts],201);
    }

    private static function subject(PDO $db,string $familyId): string{$row=self::one($db,'SELECT id FROM subjects WHERE family_id=:family_id AND title=\'Математика\' AND deleted_at IS NULL LIMIT 1',['family_id'=>$familyId]);if($row)return(string)$row['id'];return self::insert($db,'INSERT INTO subjects(id,family_id,title,description,color,is_custom) VALUES(:id,:family_id,\'Математика\',\'Базовый предмет пилотных маршрутов HomeEdu.\',\'#2563EB\',FALSE)',['family_id'=>$familyId]);}
    private static function curriculum(PDO $db,string $familyId,string $studentId): string{$year=self::schoolYear();$row=self::one($db,'SELECT id FROM curricula WHERE family_id=:family_id AND student_id=:student_id AND school_year=:year AND deleted_at IS NULL LIMIT 1',['family_id'=>$familyId,'student_id'=>$studentId,'year'=>$year]);if($row)return(string)$row['id'];return self::insert($db,'INSERT INTO curricula(id,family_id,student_id,title,school_year) VALUES(:id,:family_id,:student_id,\'4 класс\',:year)',['family_id'=>$familyId,'student_id'=>$studentId,'year'=>$year]);}
    private static function assignment(PDO $db,string $familyId,string $curriculumId,string $subjectId): string{$row=self::one($db,'SELECT id FROM curriculum_subjects WHERE curriculum_id=:curriculum AND subject_id=:subject LIMIT 1',['curriculum'=>$curriculumId,'subject'=>$subjectId]);if($row)return(string)$row['id'];return self::insert($db,'INSERT INTO curriculum_subjects(id,family_id,curriculum_id,subject_id,position) VALUES(:id,:family_id,:curriculum,:subject,0)',['family_id'=>$familyId,'curriculum'=>$curriculumId,'subject'=>$subjectId]);}
    private static function schoolYear(): string{$year=(int)date('Y');$start=(int)date('n')>=8?$year:$year-1;return $start.'/'.($start+1);}
    /** @param array<string,mixed> $params */ private static function insert(PDO $db,string $sql,array $params): string{$id=Uuid::v4();$statement=$db->prepare($sql);$statement->execute(['id'=>$id,...$params]);return$id;}
    /** @param array<string,mixed> $params @return array<string,mixed>|false */ private static function one(PDO $db,string $sql,array $params): array|false{$statement=$db->prepare($sql);$statement->execute($params);return$statement->fetch();}

    /** @return array<int,array<string,mixed>> */
    private static function definitions(): array{return[
        ['title'=>'Дробь как часть целого','description'=>'Доли, запись дроби, числитель и знаменатель.','competencies'=>['Находит равные части целого','Читает и записывает простую дробь','Объясняет роль числителя и знаменателя'],'lessons'=>[
            ['title'=>'Доля и целое','summary'=>'Учимся видеть одну или несколько равных частей.','blocks'=>['Целое можно разделить на равные части. Одна такая часть называется долей. Запись 3/8 означает, что взяли три части из восьми равных частей целого.','Пиццу разделили на 8 равных кусочков и съели 3. Съеденная часть — 3/8 пиццы.'],'quiz'=>['prompt'=>'Пирог разделили на 6 равных частей и взяли 2. Какая часть взята?','type'=>'single_choice','options'=>['2/6','6/2','2/4'],'answer'=>['options'=>[0]],'explanation'=>'Число взятых частей пишем сверху, число всех равных частей — снизу.'],'homework'=>['title'=>'Дроби вокруг нас','instructions'=>'Найди дома предмет, который можно разделить на равные части. Нарисуй его и подпиши дробью закрашенную часть.']],
            ['title'=>'Числитель и знаменатель','summary'=>'Разбираемся, что показывают числа в записи дроби.','blocks'=>['Числитель стоит над чертой и показывает, сколько частей взяли. Знаменатель стоит под чертой и показывает, на сколько равных частей разделили целое.','В дроби 5/7 числитель равен 5, а знаменатель равен 7.'],'quiz'=>['prompt'=>'Что показывает знаменатель дроби 3/8?','type'=>'single_choice','options'=>['Взяли 3 части','Целое разделили на 8 равных частей','Осталось 5 частей'],'answer'=>['options'=>[1]],'explanation'=>'Знаменатель показывает общее число равных частей.']]
        ]],
        ['title'=>'Сравнение простых дробей','description'=>'Сравнение дробей с одинаковыми знаменателями и одинаковыми числителями.','competencies'=>['Сравнивает дроби с одинаковыми знаменателями','Сравнивает единичные дроби','Обосновывает сравнение рисунком или словами'],'lessons'=>[
            ['title'=>'Одинаковые знаменатели','summary'=>'Чем больше частей взяли, тем больше дробь.','blocks'=>['Если знаменатели одинаковы, части имеют одинаковый размер. Больше та дробь, у которой больше числитель.','Сравним 2/7 и 5/7: 5/7 больше, потому что взяли пять одинаковых частей вместо двух.'],'quiz'=>['prompt'=>'Какая дробь больше?','type'=>'single_choice','options'=>['3/8','6/8','Они равны'],'answer'=>['options'=>[1]],'explanation'=>'При одинаковом знаменателе сравниваем числители.']],
            ['title'=>'Единичные дроби','summary'=>'Сравниваем доли, у которых числитель равен единице.','blocks'=>['Если целое делят на большее число равных частей, каждая часть становится меньше. Поэтому 1/3 больше 1/6.','Одна половина шоколадки больше одной четверти той же шоколадки.'],'quiz'=>['prompt'=>'Какая доля меньше?','type'=>'single_choice','options'=>['1/4','1/9','Они равны'],'answer'=>['options'=>[1]],'explanation'=>'Девятая часть меньше четвёртой, потому что целое разделено на большее число частей.'],'homework'=>['title'=>'Сравни дроби','instructions'=>'Нарисуй два одинаковых прямоугольника, покажи на них 1/3 и 1/6 и объясни, какая дробь больше.']]
        ]],
        ['title'=>'Сложение и вычитание','description'=>'Простые действия с одинаковыми знаменателями.','competencies'=>['Складывает дроби с одинаковыми знаменателями','Вычитает дроби с одинаковыми знаменателями','Проверяет, что ответ согласуется с рисунком'],'lessons'=>[
            ['title'=>'Сложение одинаковых долей','summary'=>'Складываем числители и сохраняем знаменатель.','blocks'=>['При сложении дробей с одинаковыми знаменателями складываем числители, а знаменатель оставляем прежним.','2/9 + 4/9 = 6/9: было две девятых, добавили четыре девятых, стало шесть девятых.'],'quiz'=>['prompt'=>'Вычисли 2/7 + 3/7. Укажи числитель ответа.','type'=>'number','answer'=>['value'=>5,'tolerance'=>0],'explanation'=>'2 + 3 = 5, знаменатель 7 остаётся прежним.']],
            ['title'=>'Вычитание одинаковых долей','summary'=>'Вычитаем числители и сохраняем знаменатель.','blocks'=>['При вычитании дробей с одинаковыми знаменателями вычитаем числители, а знаменатель не меняем.','7/10 − 3/10 = 4/10.'],'quiz'=>['prompt'=>'Запиши результат 6/8 − 2/8.','type'=>'short_text','answer'=>['accepted'=>['4/8','1/2']],'explanation'=>'Получаем 4/8; эту дробь также можно сократить до 1/2.'],'homework'=>['title'=>'Придумай задачу','instructions'=>'Придумай короткую жизненную задачу на сложение или вычитание дробей с одинаковыми знаменателями, реши её и объясни ход мысли.']]
        ]],
        ['title'=>'Итоговое закрепление','description'=>'Самостоятельное объяснение и применение изученного.','competencies'=>['Объясняет решение задачи с простой дробью своими словами'],'lessons'=>[
            ['title'=>'Я умею объяснять дроби','summary'=>'Собираем знания вместе и объясняем решение.','blocks'=>['В хорошем объяснении есть три части: что означает дробь, какое действие выполняем и почему ответ подходит к условию.','Задача: использовали 3/10 ленты утром и 2/10 вечером. Всего использовали 5/10 ленты, потому что 3 + 2 = 5, а размер долей не изменился.'],'quiz'=>['prompt'=>'Какие утверждения верны для 2/5 + 1/5?','type'=>'multiple_choice','options'=>['Складываем числители','Складываем знаменатели','Знаменатель остаётся 5','Ответ равен 3/5'],'answer'=>['options'=>[0,2,3]],'explanation'=>'При одинаковых знаменателях складываем только числители.'],'homework'=>['title'=>'Итоговое объяснение','instructions'=>'Реши задачу: от книги прочитали 2/8 утром и 3/8 вечером. Какая часть прочитана? Объясни решение словами и, если хочешь, приложи рисунок.']]
        ]]
    ];}
}
