import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { createQuiz, deleteQuiz, getLessonQuizzes } from '@/entities/curriculum/api'

export function QuizEditor({ lessonId }: { lessonId: string }) {
  const client = useQueryClient()
  const quizzes = useQuery({ queryKey: ['lesson-quizzes', lessonId], queryFn: () => getLessonQuizzes(lessonId) })
  const [open, setOpen] = useState(false)
  const empty = { title: 'Мини-тест', prompt: '', optionA: '', optionB: '', optionC: '', correctOption: '0', explanation: '' }
  const [form, setForm] = useState(empty)
  const refresh = async () => { await client.invalidateQueries({ queryKey: ['lesson-quizzes', lessonId] }) }
  const create = useMutation({ mutationFn: () => createQuiz(lessonId, { title: form.title, prompt: form.prompt, options: [form.optionA, form.optionB, ...(form.optionC ? [form.optionC] : [])], correctOption: Number(form.correctOption), explanation: form.explanation, position: quizzes.data?.quizzes.length ?? 0 }), onSuccess: async () => { setOpen(false); setForm(empty); await refresh() } })
  const remove = useMutation({ mutationFn: deleteQuiz, onSuccess: refresh })
  return <section className="quiz-editor"><div className="lesson-toolbar card"><div><h2>Проверка знаний</h2><p className="muted">Один вопрос с автоматической проверкой.</p></div><button onClick={() => setOpen((value) => !value)}>{open ? 'Закрыть' : '+ Добавить тест'}</button></div>{open && <form className="card quiz-form" onSubmit={(event) => { event.preventDefault(); create.mutate() }}><label className="field"><span>Название</span><input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label className="field"><span>Вопрос</span><textarea required rows={3} value={form.prompt} onChange={(event) => setForm({ ...form, prompt: event.target.value })} /></label><div className="form-row"><label className="field"><span>Вариант 1</span><input required value={form.optionA} onChange={(event) => setForm({ ...form, optionA: event.target.value })} /></label><label className="field"><span>Вариант 2</span><input required value={form.optionB} onChange={(event) => setForm({ ...form, optionB: event.target.value })} /></label></div><label className="field"><span>Вариант 3 (необязательно)</span><input value={form.optionC} onChange={(event) => setForm({ ...form, optionC: event.target.value })} /></label><label className="field"><span>Правильный вариант</span><select value={form.correctOption} onChange={(event) => setForm({ ...form, correctOption: event.target.value })}><option value="0">Вариант 1</option><option value="1">Вариант 2</option>{form.optionC && <option value="2">Вариант 3</option>}</select></label><label className="field"><span>Объяснение после ответа</span><textarea rows={2} value={form.explanation} onChange={(event) => setForm({ ...form, explanation: event.target.value })} /></label>{create.error && <p className="form-error">{create.error.message}</p>}<button disabled={create.isPending}>Сохранить тест</button></form>}<div className="quiz-list">{quizzes.data?.quizzes.map((quiz) => <article className="card" key={quiz.id}><div className="lesson-card-heading"><span className="badge">Тест</span><button className="icon-button icon-danger" aria-label={`Удалить ${quiz.title}`} onClick={() => remove.mutate(quiz.id)}>×</button></div><h3>{quiz.title}</h3><p>{quiz.question.prompt}</p><ol>{quiz.question.options.map((option, index) => <li className={index === quiz.question.correctOption ? 'correct-option' : ''} key={`${index}-${option}`}>{option}</li>)}</ol></article>)}</div></section>
}
