import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { getReviewSubmissions,reviewSubmission,type ReviewSubmission } from '@/entities/homework/api'

function ReviewCard({item,refresh}:{item:ReviewSubmission;refresh:()=>Promise<unknown>}){
  const [comment,setComment]=useState('');const [grade,setGrade]=useState('5')
  const review=useMutation({mutationFn:(decision:'accepted'|'needs_revision')=>reviewSubmission(item.id,{decision,grade:decision==='accepted'?Number(grade):null,comment}),onSuccess:refresh})
  return <article className="card review-card" style={{borderLeftColor:item.subjectColor}}><div className="lesson-card-heading"><span className="badge">{item.studentName} · {item.subjectTitle}</span><span className={`lesson-status status-${item.status}`}>{item.status==='submitted'?'Ждёт проверки':item.status==='needs_revision'?'На доработке':'Проверено'}</span></div><h2>{item.title}</h2><p className="muted">{item.lessonTitle}</p><details><summary>Условие задания</summary><p>{item.instructions}</p></details><div className="submitted-answer"><strong>Ответ ученика</strong><p>{item.responseText}</p></div>{item.status==='submitted'&&<div className="review-form"><label className="field"><span>Комментарий</span><textarea required rows={3} value={comment} onChange={(event)=>setComment(event.target.value)}/></label><label className="field"><span>Оценка при принятии</span><select value={grade} onChange={(event)=>setGrade(event.target.value)}>{[5,4,3,2].map((value)=><option key={value}>{value}</option>)}</select></label><div className="review-actions"><button className="button-danger" disabled={!comment.trim()||review.isPending} onClick={()=>review.mutate('needs_revision')}>Вернуть на доработку</button><button disabled={!comment.trim()||review.isPending} onClick={()=>review.mutate('accepted')}>Принять работу</button></div>{review.error&&<p className="form-error">{review.error.message}</p>}</div>}</article>
}

export function ReviewQueuePage(){const client=useQueryClient();const queue=useQuery({queryKey:['review-submissions'],queryFn:getReviewSubmissions});const refresh=async()=>{await client.invalidateQueries({queryKey:['review-submissions']})};return <><header className="page-header"><p className="eyebrow">Проверка работ</p><h1>Домашние задания</h1><p className="muted">Ответы Сары и Давида, ожидающие решения родителя.</p></header>{queue.error&&<p className="form-error">{queue.error.message}</p>}{queue.isLoading?<p>Загружаем работы…</p>:queue.data?.submissions.length?<section className="review-list">{queue.data.submissions.map((item)=><ReviewCard key={item.id} item={item} refresh={refresh}/>)}</section>:<section className="card empty"><h2>Новых работ нет</h2><p className="muted">Отправленные ответы появятся здесь.</p></section>}</>}
